PTKidsBITIoT.motorWrite(Motor_Write.Motor_1, 100)
basic.pause(500)
PTKidsBITIoT.motorWrite(Motor_Write.Motor_2, -100)
basic.pause(500)
PTKidsBITIoT.motorStop()
basic.pause(500)
PTKidsBITIoT.Turn(_Turn.Left, 100)
basic.pause(500)
PTKidsBITIoT.Spin(_Spin.Right, 100)
basic.pause(500)
PTKidsBITIoT.servoWrite(Servo_Write.S0, 180)
basic.pause(500)
PTKidsBITIoT.servoWrite(Servo_Write.S0, 90)
basic.forever(function () {
    basic.showNumber(PTKidsBITIoT.ADCRead(ADC_Read.ADC0))
})